[package]
name = "kernel-splat"
description = "hogehoge"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

[build-dependencies]
bindgen_cuda.workspace = true
