[workspace]
members = [
    "kernels"]
resolver = "2"

[package]
name = "del-cudarc"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies.cudarc]
version = "*"
features = [
    "std", "cublas", "cublaslt", "curand", "driver", "nvrtc",
    "f16", "cuda-version-from-build-system", "dynamic-linking"]
default-features=false

[dependencies]
anyhow = "1.0.93"
rand = "0.8.5"
rand_chacha = "0.3.1"

# internal
kernels = { path = "kernels" }



