[workspace]
members = [
    "del-fem-cudarc",
    "del-fem-cudarc-kernel",
    "del-cudarc-splat",
    "del-cudarc-util",
    "del-cudarc-bvh",
    "demos-gl",
    "kernel-splat",
    "kernel-util",
    "kernel-bvh"]
resolver = "2"

[workspace.package]
name = "del-cudarc"
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies.cudarc]
version = "*"
features = [
    "std", "cublas", "cublaslt", "curand", "driver", "nvrtc",
    "f16", "cuda-version-from-build-system", "dynamic-linking"]
default-features=false

[workspace.dependencies]
anyhow = "1.0.89"
num-traits = "0.2.19"
slice-of-array = "0.3.2"
itertools = "0.13.0"
image = "0.25.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
arrayref = "0.3.9"
# opengl
glutin = "0.32.0"
glutin-winit = "0.5.0"
winit = "0.30.5"
raw-window-handle = "0.6.2"
gl_generator = "0.14"
cfg_aliases = "0.2.1"
# build dependncy
bindgen_cuda = "0.1.5"

# internal
kernel-splat = { path = "kernel-splat" }
kernel-util = { path = "kernel-util" }
kernel-bvh = { path = "kernel-bvh" }
del-cudarc-splat = { path = "del-cudarc-splat" }
del-fem-cudarc-kernel = { path = "del-fem-cudarc-kernel" }
del-cudarc-util = {path = "del-cudarc-util"}
del-cudarc-bvh = { path = "del-cudarc-bvh"}

# workspace
del-msh-core = { path = "../del-msh/del-msh-core" }
del-geo-core = { path = "../del-geo/del-geo-core" }
del-gl-core = { path = "../del-gl/del-gl-core" }
del-gl-winit-glutin = { path = "../del-gl/del-gl-winit-glutin" }
del-canvas-cpu = { path = "../del-canvas/del-canvas-cpu" }
del-canvas-image = { path = "../del-canvas/del-canvas-image" }
del-raycast-core = {path = "../del-raycast/del-raycast-core"}


