[package]
name = "del-fem-cudarc"
description = "hogehoge"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
del-msh-core.workspace = true
del-fem-cudarc-kernel.workspace = true
cudarc.workspace = true



