[package]
name = "del-cudarc-safe"
description = "utility funcs for cudarc"
version = "0.1.2"
edition = "2024"
license = "MIT"

[dependencies]
del-cudarc-kernel.workspace = true
cudarc.workspace = true

[dev-dependencies]
rand.workspace = true
rand_chacha.workspace = true


