name: Rust CI (Self-hosted)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose -- --test-threads=1

      - name: Run Clippy (Linter)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Python test
        run: |
          python -m venv venv
          ./venv/Scripts/activate
          pip install maturin
          pip install pytest
          pip install numpy
          pip install torch
          cd del-cudarc-dlpack
          maturin develop
          python tests/rust_interop0.py
          
