name: Rust CI (Self-hosted)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions/setup-rust@v2
        with:
          rust-version: stable

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose